##Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import sklearn
import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [2]:
df = pd.read_csv('RiverDataResult.csv')

In [3]:
print(df.shape)

(2326, 22)


In [4]:
df.head()

Date      Time   Temp   pH   ...   WTDS     WDO     WQI  Result
0  17-02-2020  17:04:52  20.67  8.40  ...  9.625  35.625  70.990       4
1  17-02-2020  17:05:02  20.67  8.40  ...  9.625  35.625  69.235       3
2  17-02-2020  17:05:12  20.67  8.40  ...  9.625  35.625  70.990       4
3  17-02-2020  17:05:22  20.67  8.40  ...  9.625  35.625  70.990       4
4  17-02-2020  17:05:32  20.68  8.41  ...  9.625  35.625  69.235       3

[5 rows x 22 columns]

#Train Test Splitting

In [5]:
X = df.iloc[:,[3,7,10,11]]

In [6]:
print(X)

       pH   TDS   D.O.  Turbidity
0     8.40  306  101.5       36.7
1     8.40  305  101.4       42.4
2     8.40  305  101.5       38.2
3     8.40  305  101.7       38.0
4     8.41  305  101.7       46.8
...    ...  ...    ...        ...
2321  8.94  299  124.9       12.3
2322  8.96  297  125.6       11.9
2323  8.98  296  125.9       11.8
2324  8.95  297  125.7       11.6
2325  8.93  299  125.7       13.6

[2326 rows x 4 columns]


In [7]:
Y=df['Result']

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=45)

X_train = X_train.values
X_test = X_test.values

Y_train = Y_train.values
Y_test = Y_test.values

#Scaling

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

#Model

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
clf = LogisticRegression(multi_class='multinomial', solver='newton-cg')
clf.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)

#Prediction

In [13]:
Y_predl = clf.predict(X_test)

In [14]:
Y_predla = clf.predict(X_train)
acc2 = accuracy_score(Y_train, Y_predla)
print(acc2);

0.9191270860077022


#Accuracy


In [15]:
acc =  accuracy_score(Y_test, Y_predl)
cm = confusion_matrix(Y_test, Y_predl)
print(acc)
print(cm)

0.9127604166666666
[[  2   0   0]
 [  0 361  10]
 [  0  57 338]]


#Loss

In [16]:
pra = clf.predict_proba(X_test)
sklearn.metrics.log_loss(Y_test, pra,eps=1e-15, normalize=True, sample_weight=None, labels=None)

0.3686610762738249