#Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import sklearn
import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

#Importing dataset

In [2]:
df = pd.read_csv('RiverDataResult.csv')

In [3]:
print(df.shape)

(2326, 22)


In [4]:
df.head()

Date      Time   Temp   pH   ...   WTDS     WDO     WQI  Result
0  17-02-2020  17:04:52  20.67  8.40  ...  9.625  35.625  70.990       4
1  17-02-2020  17:05:02  20.67  8.40  ...  9.625  35.625  69.235       3
2  17-02-2020  17:05:12  20.67  8.40  ...  9.625  35.625  70.990       4
3  17-02-2020  17:05:22  20.67  8.40  ...  9.625  35.625  70.990       4
4  17-02-2020  17:05:32  20.68  8.41  ...  9.625  35.625  69.235       3

[5 rows x 22 columns]

#Splitting

In [5]:
X = df.iloc[:,[3,7,10,11]]

In [6]:
print(X)

       pH   TDS   D.O.  Turbidity
0     8.40  306  101.5       36.7
1     8.40  305  101.4       42.4
2     8.40  305  101.5       38.2
3     8.40  305  101.7       38.0
4     8.41  305  101.7       46.8
...    ...  ...    ...        ...
2321  8.94  299  124.9       12.3
2322  8.96  297  125.6       11.9
2323  8.98  296  125.9       11.8
2324  8.95  297  125.7       11.6
2325  8.93  299  125.7       13.6

[2326 rows x 4 columns]


In [7]:
Y=df['Result']

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=45)

X_train = X_train.values
X_test = X_test.values

Y_train = Y_train.values
Y_test = Y_test.values

#Scaling

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

#Model

In [11]:
from sklearn.naive_bayes import GaussianNB

#Continuous data, normal distribution, supervised ML algo = Gaussian NB.

In [12]:
modex = GaussianNB().fit(X_train, Y_train)

#Prediction

In [13]:
predmodex = modex.predict(X_test)
print(np.mean(predmodex == Y_test))

0.7786458333333334


In [14]:
print(confusion_matrix(Y_test, predmodex))

[[  2   0   0]
 [  7 221 143]
 [  0  20 375]]


In [15]:
predmo = modex.predict(X_train)
acc4 = accuracy_score(Y_train, predmo)
print(acc4);

0.7464698331193839


In [16]:
print(accuracy_score(Y_test, predmodex))

0.7786458333333334


#Loss

In [17]:
praa = modex.predict_proba(X_test)
sklearn.metrics.log_loss(Y_test, praa,eps=1e-15, normalize=True, sample_weight=None, labels=None)

0.8413975528557293